project_id = "htgqgtwbbrzbadusvtxg"

[functions.analyze-request]
verify_jwt = false

[functions.invoice-mentor]
verify_jwt = false

[functions.pro-admin-assistant]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.quote-to-invoice]
verify_jwt = false

[functions.translate-cv]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.premium-consultation]
verify_jwt = false
