import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

/**
 * PROTECTED TRANSLATIONS DICTIONARY
 * 
 * ⚠️ RÈGLES STRICTES:
 * 1. FRANÇAIS: Professionnel, précis, jargon administratif français
 * 2. ARABE: Mélange de Darija et arabe clair - PAS de traduction mot-à-mot
 * 3. TERMES PROTÉGÉS (ne JAMAIS modifier):
 *    - عرض سعر (دوفي)
 *    - فاتورة (فاكتير)
 *    - عشان ما تتلخبطش حول الدوفي لفاكتير
 */
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // ===== NAVIGATION =====
    'nav.dashboard': 'Accueil',
    'nav.radio': 'Radio',
    'nav.assistant': 'Conseils',
    'nav.profile': 'Mon Profil',
    'nav.pro': 'Outils',
    'nav.admin': 'Admin',

    // ===== HEADER =====
    'header.appName': 'Anafy Pro',
    'header.consultations': 'Consultations',
    'header.proTools': 'Outils Pro',
    
    // ===== DASHBOARD =====
    'dashboard.welcome': 'Bienvenue sur Anafy Pro',
    'dashboard.subtitle': 'Votre assistant administratif intelligent',
    'dashboard.quickAccess': 'Accès Rapide',
    'dashboard.radioCard': 'Radio Égyptienne',
    'dashboard.radioDesc': 'Écoutez vos stations préférées',
    'dashboard.assistantCard': 'Assistant IA',
    'dashboard.assistantDesc': 'Rédigez vos courriers administratifs',
    'dashboard.aiBanner': 'Posez-moi vos questions',
    'dashboard.aiBannerSub': 'En français et en arabe',
    'dashboard.cvCard': 'Mon CV Pro',
    'dashboard.cvCardSub': 'Mon CV Pro',
    'dashboard.invoiceCard': 'Devis, Factures & Étude de Rentabilité IA',
    'dashboard.invoiceCardSub': 'Devis, Factures & Étude de Rentabilité IA',
    'dashboard.codeRoute': 'Code de la Route',
    'dashboard.codeRouteSub': 'Cours et tests en français',
    
    // ===== CHAT QUICK ACTIONS =====
    'chat.action.cv': 'Faire un CV',
    'chat.action.invoice': 'Faire une Facture',
    'chat.action.mail': 'Répondre Courrier',
    'chat.title': 'Assistant Admin',
    'chat.subtitle': 'Posez vos questions',
    'chat.placeholder': 'Écrivez votre message...',
    'chat.thinking': 'Réflexion...',
    'chat.welcomeTitle': 'Bonjour ! Je suis votre assistant intelligent',
    'chat.welcomeMessage': 'Décrivez votre situation ou téléchargez un document.',
    
    // ===== RADIO =====
    'radio.title': 'Radio',
    'radio.nowPlaying': 'En cours de lecture',
    'radio.selectStation': 'Sélectionnez une station',
    'radio.searchPlaceholder': 'Rechercher une station...',
    'radio.categoryEgypt': 'Radios Égyptiennes (Musique & News)',
    'radio.categoryMaghreb': 'Radios Maghreb & France',
    'radio.noResults': 'Aucune station trouvée',
    
    // ===== ASSISTANT / CONSULTATIONS =====
    'assistant.title': 'Discussion',
    'assistant.subtitle': 'Décrivez votre situation et recevez une lettre professionnelle',
    'assistant.textPlaceholder': 'Décrivez votre situation en détail...',
    'assistant.recordVoice': 'Enregistrer',
    'assistant.uploadDocument': 'Télécharger un document',
    'assistant.analyze': 'Analyser',
    'assistant.formalLetter': 'Lettre Officielle',
    'assistant.legalNote': 'Note Juridique',
    'assistant.actionPlan': 'Plan d\'Action',
    'assistant.copy': 'Copier',
    'assistant.download': 'Télécharger PDF',
    'assistant.newTopic': 'Nouveau sujet',
    'assistant.continueSession': 'Reprendre',
    'assistant.startNew': 'Nouveau sujet',
    'assistant.sessionDialog.title': 'Conversation précédente',
    'assistant.sessionDialog.description': 'Voulez-vous reprendre votre conversation précédente ou commencer un nouveau sujet ?',
    'assistant.clearConfirm.title': 'Effacer la conversation ?',
    'assistant.clearConfirm.description': 'Cette action effacera tout l\'historique de la conversation.',
    'assistant.dailyLimit': 'Limite quotidienne atteinte',
    'assistant.dailyLimitDesc': 'Limite quotidienne atteinte (30 messages). À demain !',
    'assistant.analyzing': 'Analyse en cours...',
    'assistant.documentReady': 'Document prêt',
    'assistant.viewDocument': 'Voir le document',
    'assistant.generateLetter': 'Générer une lettre',
    'assistant.generating': 'Génération...',
    
    // ===== PROFILE =====
    'profile.title': 'Mon Profil',
    'profile.fullName': 'Nom Complet',
    'profile.firstName': 'Prénom',
    'profile.lastName': 'Nom',
    'profile.address': 'Adresse',
    'profile.phone': 'Téléphone',
    'profile.cafNumber': 'Numéro CAF',
    'profile.foreignerNumber': 'Numéro Étranger',
    'profile.socialSecurity': 'N° Sécurité Sociale (Carte Vitale)',
    'profile.save': 'Enregistrer',
    'profile.optional': '(optionnel)',
    'profile.saved': 'Profil enregistré',
    'profile.savedDesc': 'Vos informations ont été sauvegardées.',
    
    // ===== PRO TOOLS =====
    'pro.title': 'Votre Bras Droit',
    'pro.subtitle': 'Outils pour artisans et indépendants',
    'pro.invoices': 'Devis & Factures',
    'pro.invoicesDesc': 'Créez vos devis et factures facilement',
    'pro.quoteToInvoice': 'Devis → Facture',
    'pro.quoteToInvoiceDesc': 'L\'IA remplit votre facture automatiquement',
    'pro.legal': 'Guide Juridique',
    'pro.legalDesc': 'Comprendre le droit du travail et les impôts',
    'pro.cvGenerator': 'Générateur de CV',
    'pro.cvGeneratorDesc': 'Écrivez en arabe, l\'IA traduit en français',
    'pro.cvGeneratorDesc2': 'Un CV professionnel en quelques minutes',
    'pro.settings': 'Mon identité pro',
    'pro.settingsDesc': 'Infos entreprise et logo',
    'pro.toolsNotice': 'Outils dédiés aux artisans en France',
    
    // ===== INVOICE CREATOR =====
    'invoice.quote': 'Devis',
    'invoice.invoice': 'Facture',
    'invoice.client': 'Client',
    'invoice.clientName': 'Nom du client',
    'invoice.clientAddress': 'Adresse du client',
    'invoice.worksite': 'Adresse du chantier',
    'invoice.description': 'Description',
    'invoice.quantity': 'Quantité',
    'invoice.unit': 'Unité',
    'invoice.unitPrice': 'Prix unitaire',
    'invoice.total': 'Total',
    'invoice.subtotal': 'Sous-total HT',
    'invoice.tva': 'TVA',
    'invoice.totalTTC': 'Total TTC',
    'invoice.addLine': 'Ajouter une ligne',
    'invoice.preview': 'Aperçu & Télécharger PDF',
    'invoice.signature': 'Signature',
    'invoice.clientSignature': 'Signature du client',
    'invoice.artisanSignature': 'Signature du prestataire',
    'invoice.bonPourAccord': 'Bon pour accord',
    'invoice.validUntil': 'Devis valable jusqu\'au',
    'invoice.paymentTerms': 'Conditions de paiement',
    
    // ===== CV GENERATOR =====
    'cv.title': 'Mon CV',
    'cv.subtitle': 'Rédigez en arabe, l\'IA traduit en français professionnel',
    'cv.personalInfo': 'Informations personnelles',
    'cv.fullName': 'Nom complet',
    'cv.firstName': 'Prénom',
    'cv.lastName': 'Nom',
    'cv.profession': 'Métier / Poste souhaité',
    'cv.email': 'Email',
    'cv.phone': 'Téléphone',
    'cv.address': 'Adresse',
    'cv.summary': 'Résumé professionnel',
    'cv.experience': 'Expérience professionnelle',
    'cv.education': 'Formation',
    'cv.skills': 'Compétences',
    'cv.languages': 'Langues',
    'cv.translate': 'Traduire en français',
    'cv.translating': 'Traduction en cours...',
    'cv.downloadPdf': 'Télécharger PDF',
    'cv.preview': 'Aperçu',
    'cv.edit': 'Éditer',
    'cv.drivingLicense': 'Permis de conduire',
    'cv.interests': 'Centres d\'intérêt',
    
    // ===== COMMON =====
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.close': 'Fermer',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.or': 'ou',
    'common.and': 'et',
    'common.send': 'Envoyer',
    
    // ===== ERRORS =====
    'error.network': 'Erreur de connexion. Veuillez réessayer.',
    'error.timeout': 'La requête a pris trop de temps. Veuillez réessayer.',
    'error.generic': 'Une erreur est survenue. Veuillez réessayer.',
    'error.invalidAlphabet': 'Caractères non autorisés détectés. Utilisez uniquement le français ou l\'arabe.',
    
    // ===== AUTH =====
    'auth.login': 'Se connecter',
    'auth.signup': 'S\'inscrire',
    'auth.logout': 'Se déconnecter',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.forgotPassword': 'Mot de passe oublié ?',

    // ===== NEWS =====
    'news.title': 'Actualités',
    'news.subtitle': 'Suivez l\'info en direct',
    'news.disclaimer': 'Liens vers des sources externes. Anafy Pro n\'est pas responsable du contenu.',
    'nav.news': 'Actus',

    // ===== COURRIER =====
    'courrier.title': 'Répondre au Courrier',

    // ===== LEGAL GUIDE =====
    'legal.title': 'Guide Juridique',
    'legal.subtitle': 'Analyse de documents active',
    'legal.welcome': 'Bienvenue dans votre guide administratif et juridique.',
    'legal.welcomeSub': 'Envoyez une photo de document ou posez vos questions sur vos droits.',
    'legal.placeholder': 'Décrivez votre situation ou envoyez un document...',
    'legal.dashboardTitle': 'Guide Juridique',
    'legal.dashboardSub': 'Analyse Documents & Droits',



    // ===== EXPENSES / GESTION COMPTABLE =====
    'expenses.notLoggedIn': 'Veuillez vous connecter',
    'expenses.warningTip': 'Ces chiffres sont basés uniquement sur vos factures — consultez votre comptable pour les calculs exacts',
    'expenses.title': '💰 Gestion Comptable',
    'expenses.btn.scan': 'Scanner',
    'expenses.btn.add': 'Ajouter',
    'expenses.btn.accountantExport': 'Export comptable',
    'expenses.btn.archiveDocs': 'Archive documents',
    'expenses.section.accounting': 'Comptabilité',
    'expenses.section.documents': 'Documents',
    'expenses.section.clients': 'Clients',
    'expenses.section.chantiers': 'Chantiers',
    'expenses.summary.collected': '💰 Trésorerie encaissée',
    'expenses.summary.totalExpenses': 'Total Dépenses',
    'expenses.timeline.title': '📋 Dernières Opérations',
    'expenses.timeline.empty': 'Aucune opération enregistrée',
    'expenses.filter.paidAll': 'Toutes factures',
    'expenses.filter.paidOnly': 'Payées',
    'expenses.filter.unpaidOnly': 'Impayées',
    'expenses.filter.all': 'Tout',
    'expenses.filter.month': 'Ce mois',
    'expenses.filter.quarter': 'Ce trimestre',
    'expenses.filter.year': 'Cette année',
    'expenses.badge.overdue': 'En retard',
    'expenses.diagnostic.label': '🧪 Diagnostic : {n} facture(s) marquée(s) payée(s)',
    'expenses.diagnostic.desc': 'Si ce sont des données de test, réinitialisez-les à « impayé » par client.',
    'expenses.diagnostic.resetAllBtn': 'Tout réinitialiser ({n})',
    'expenses.diagnostic.resetAllTitle': 'Réinitialiser toutes les factures payées',
    'expenses.diagnostic.resetAllDialogDesc': '{n} facture(s) seront marquées comme impayées. Aucun document ne sera supprimé.',
    'expenses.diagnostic.unpaidBtn': 'Impayé',
    'expenses.diagnostic.resetClientTitle': 'Confirmer la réinitialisation',
    'expenses.diagnostic.resetClientDialogDesc': '{n} facture(s) de « {name} » ({total}) seront marquées comme impayées. Aucun document ne sera supprimé.',
    'expenses.admin.title': '🛠️ Outils administrateur',
    'expenses.admin.desc': "Marque toutes les factures comme impayées et supprime toutes les dépenses. Aucune facture ni devis n'est supprimé.",
    'expenses.admin.resetBtn': 'Réinitialiser les données de test',
    'expenses.admin.resetDialogDesc': 'Toutes les factures passeront en « impayé » et toutes les dépenses seront supprimées. Aucune facture ni devis ne sera supprimé.',
    'expenses.toast.resetOk': '✅ Réinitialisé',
    'expenses.toast.resetClientDesc': 'Factures de {name} marquées comme impayées',
    'expenses.toast.resetAllDesc': '{n} facture(s) marquée(s) comme impayées',
    'expenses.toast.resetTestDataTitle': '✅ Données de test réinitialisées',
    'expenses.toast.resetTestDataDesc': 'Toutes les factures sont impayées et toutes les dépenses ont été supprimées.',
    'expenses.toast.accountantEmailMissingTitle': 'Email comptable manquant',
    'expenses.toast.accountantEmailMissingDesc': "Ajoutez l'email du comptable dans les paramètres",
    'expenses.toast.accountantSentTitle': '✅ Documents envoyés au comptable',
    'expenses.toast.accountantSentDesc': 'Envoyé à : {email}',
    'expenses.toast.sendFailedTitle': "Échec de l'envoi",
    'expenses.toast.sendFailedDesc': 'Veuillez réessayer',
    'expenses.toast.archiveEmptyTitle': 'Archive vide',
    'expenses.toast.archiveEmptyDesc': 'Aucun fichier attaché trouvé',
    'expenses.toast.archiveOkTitle': 'Archive téléchargée',
    'expenses.toast.archiveOkDesc': '{n} fichier(s) archivé(s)',
    'expenses.toast.archiveErrorDesc': "Échec du téléchargement de l'archive",
    // ===== AddExpenseModal =====
    'addExpense.title': 'Ajouter une dépense',
    'addExpense.receipt.label': 'Photo du reçu',
    'addExpense.receipt.change': 'Changer',
    'addExpense.receipt.analyze': 'Analyser',
    'addExpense.receipt.camera': '📷 Prendre une photo',
    'addExpense.receipt.gallery': '🖼️ Choisir un fichier',
    'addExpense.field.title': 'Titre *',
    'addExpense.field.titlePlaceholder': 'Ex: Achat peinture',
    'addExpense.field.amount': 'Montant (€) *',
    'addExpense.field.tva': 'TVA (€)',
    'addExpense.field.amountType': 'Le montant saisi est en *',
    'addExpense.field.category': 'Catégorie',
    'addExpense.field.date': 'Date',
    'addExpense.field.client': 'Sélectionner un client',
    'addExpense.field.clientPlaceholder': 'Choisir un client...',
    'addExpense.field.chantier': 'Sélectionner un chantier',
    'addExpense.field.chantierPlaceholder': 'Choisir un chantier...',
    'addExpense.field.docLink': 'Lier à un document (optionnel)',
    'addExpense.field.docLinkPlaceholder': 'Choisir un devis ou facture',
    'addExpense.field.docLinkNone': 'Aucun',
    'addExpense.field.notes': 'Notes',
    'addExpense.field.notesPlaceholder': 'Notes supplémentaires...',
    'addExpense.save': 'Enregistrer la dépense',
    'addExpense.toast.analyzeOk': '✅ Analyse réussie',
    'addExpense.toast.analyzeErr': "⚠️ Erreur d'analyse",
    'addExpense.toast.analyzeErrDesc': 'Réessayez ou saisissez manuellement',
    'addExpense.toast.missingTitle': '⚠️ Données manquantes',
    'addExpense.toast.missingDesc': 'Titre et montant sont obligatoires',
    'addExpense.toast.added': '✅ Dépense ajoutée',
    'addExpense.toast.err': '❌ Erreur',
    'addExpense.cat.materials': 'Matériaux',
    'addExpense.cat.tools': 'Outils',
    'addExpense.cat.transport': 'Transport',
    'addExpense.cat.food': 'Repas',
    'addExpense.cat.office': 'Fournitures',
    'addExpense.cat.insurance': 'Assurance',
    'addExpense.cat.telecom': 'Télécom',
    'addExpense.cat.other': 'Autre',

    // ===== SUPPLIER INVOICES (LIST) =====
    'supplierInvoices.title': 'Factures Fournisseurs',
    'supplierInvoices.count.suffix': 'facture(s)',
    'supplierInvoices.ttcSuffix': 'TTC',
    'supplierInvoices.import': 'Importer une facture',
    'supplierInvoices.source.label': 'Source',
    'supplierInvoices.source.all': 'Tous',
    'supplierInvoices.empty': "Aucune facture fournisseur pour l'instant",
    'supplierInvoices.noSupplier': 'Sans fournisseur',
    'supplierInvoices.htPrefix': 'HT',
    'supplierInvoices.status.received': 'Reçue',
    'supplierInvoices.status.processed': 'Traitée',
    'supplierInvoices.status.paid': 'Payée',
    'supplierInvoices.toast.loadError': 'Erreur de chargement',
    // ===== SUPPLIER INVOICE DETAIL =====
    'supplierInvoiceDetail.back': 'Retour',
    'supplierInvoiceDetail.noSupplier': 'Sans fournisseur',
    'supplierInvoiceDetail.siret': 'SIRET',
    'supplierInvoiceDetail.date': 'Date',
    'supplierInvoiceDetail.source': 'Source',
    'supplierInvoiceDetail.supplierReference': 'Réf. fournisseur',
    'supplierInvoiceDetail.amountHT': 'Montant HT',
    'supplierInvoiceDetail.tva': 'TVA',
    'supplierInvoiceDetail.ttc': 'TTC',
    'supplierInvoiceDetail.chantier.title': 'Chantier associé',
    'supplierInvoiceDetail.chantier.placeholder': 'Sélectionner un chantier',
    'supplierInvoiceDetail.chantier.none': '— Aucun chantier —',
    'supplierInvoiceDetail.chantier.remove': 'Retirer',
    'supplierInvoiceDetail.chantier.note': 'Ne modifie ni le montant, ni la TVA, ni le PDF, ni la comptabilité.',
    'supplierInvoiceDetail.chantier.toastAttached': 'Facture fournisseur rattachée au chantier.',
    'supplierInvoiceDetail.chantier.toastDetached': 'Facture fournisseur retirée du chantier.',
    'supplierInvoiceDetail.expense.title': 'Dépense associée',
    'supplierInvoiceDetail.expense.placeholder': 'Sélectionner une dépense',
    'supplierInvoiceDetail.expense.none': '— Aucune dépense —',
    'supplierInvoiceDetail.expense.alreadyLinked': 'déjà liée',
    'supplierInvoiceDetail.expense.note': "Associer cette facture fournisseur à la dépense OCR correspondante évite tout double comptage dans la rentabilité du chantier.",
    'supplierInvoiceDetail.expense.toastAttached': 'Dépense rattachée à la facture fournisseur.',
    'supplierInvoiceDetail.expense.toastDetached': 'Dépense détachée.',
    'supplierInvoiceDetail.lines.title': 'Lignes',
    'supplierInvoiceDetail.accounting.title': 'Comptabilité — Journal ACH',
    'supplierInvoiceDetail.accounting.subtitle': "Écritures générées automatiquement et incluses dans l'export FEC",
    'supplierInvoiceDetail.accounting.account': 'Compte',
    'supplierInvoiceDetail.accounting.label': 'Libellé',
    'supplierInvoiceDetail.accounting.debit': 'Débit',
    'supplierInvoiceDetail.accounting.credit': 'Crédit',
    'supplierInvoiceDetail.accounting.total': 'Total',
    'supplierInvoiceDetail.accounting.purchases': 'Achats matières premières',
    'supplierInvoiceDetail.accounting.tvaDeductible': 'TVA déductible',
    'supplierInvoiceDetail.accounting.suppliers': 'Fournisseurs',
    'supplierInvoiceDetail.viewOriginal': 'Voir la facture originale',
    'supplierInvoiceDetail.downloadOriginal': 'Télécharger la facture originale',
    'supplierInvoiceDetail.originalUnavailable': 'Facture originale temporairement indisponible',
    'supplierInvoiceDetail.originalMissing': 'Justificatif original non disponible',
    'supplierInvoiceDetail.markPaid': 'Marquer comme payée',
    'supplierInvoiceDetail.markPaidToast': 'Marquée comme payée',
    'supplierInvoiceDetail.genericError': 'Une erreur est survenue',

    // ===== CHANTIER DETAIL =====
    'chantierDetail.loading': 'Chargement...',
    'chantierDetail.notFound': 'Chantier introuvable',
    'chantierDetail.status.etude': 'Étude',
    'chantierDetail.status.devis_envoye': 'Devis envoyé',
    'chantierDetail.status.en_cours_travaux': 'En cours de travaux',
    'chantierDetail.status.facture_envoyee': 'Facture envoyée',
    'chantierDetail.status.paiement_attente': 'Paiement en attente',
    'chantierDetail.status.facture_payee': 'Facture payée',
    'chantierDetail.alert.red': 'Danger : Les dépenses dépassent le budget ! Profit en danger',
    'chantierDetail.alert.yellow': 'Attention : Les dépenses approchent du budget défini',
    'chantierDetail.budget.title': 'Budget du projet',
    'chantierDetail.budget.edit': 'Modifier',
    'chantierDetail.budget.expected': 'Budget prévu',
    'chantierDetail.budget.invoiced': 'Montant facturé',
    'chantierDetail.budget.progress': 'Avancement budgétaire',
    'chantierDetail.budget.label': 'Budget du projet (€)',
    'chantierDetail.budget.save': 'OK',
    'chantierDetail.budget.cancel': '✕',
    'chantierDetail.budget.add': '+ Ajouter un budget',
    'chantierDetail.budget.savedToast': 'Budget enregistré ✓',
    'chantierDetail.toast.errorTitle': 'Erreur',
    'chantierDetail.toast.saveError': "Impossible d'enregistrer le budget",
    'chantierDetail.actions.createInvoice': 'Créer Facture',
    'chantierDetail.actions.addExpense': 'Ajouter Dépense',
    'chantierDetail.synthese.devis': 'Devis',
    'chantierDetail.synthese.devisHint': 'Indicatif',
    'chantierDetail.synthese.factured': 'Facturé',
    'chantierDetail.synthese.encaisse': 'Encaissé',
    'chantierDetail.synthese.reste': 'Reste à encaisser',
    'chantierDetail.synthese.expenses': 'Dépenses',
    'chantierDetail.synthese.suppliers': 'Fact. fournisseurs',
    'chantierDetail.marginNote': 'Marge disponible après consolidation des dépenses. Estimation fondée sur les documents actuellement rattachés à ce chantier.',
    'chantierProfitability.title': 'Rentabilité du chantier',
    'chantierProfitability.status.rentable': 'Chantier rentable',
    'chantierProfitability.status.surveiller': 'Chantier à surveiller',
    'chantierProfitability.status.deficitaire': 'Chantier déficitaire',
    'chantierProfitability.status.incomplet': 'Calcul incomplet',
    'chantierProfitability.revenueHT': 'CA HT',
    'chantierProfitability.costsHT': 'Coûts HT',
    'chantierProfitability.marginHT': 'Marge HT',
    'chantierProfitability.freeExpensesHT': 'Dépenses libres HT',
    'chantierProfitability.supplierHT': 'Fact. fournisseurs HT',
    'chantierProfitability.antiDoublonNote': "Estimation HT. Anti-doublon : les dépenses liées à une facture fournisseur ne sont comptées qu'une fois (via la facture).",
    'chantierDetail.tabs.documents': 'Documents',
    'chantierDetail.tabs.expenses': 'Dépenses',
    'chantierDetail.tabs.suppliers': 'Fournisseurs',
    'chantierDetail.tabs.reports': 'Rapports',
    'chantierDetail.docs.errorPrefix': 'Documents indisponibles',
    'chantierDetail.docs.devisSection': 'Devis',
    'chantierDetail.docs.noDevis': 'Aucun devis associé à ce chantier.',
    'chantierDetail.docs.converted': 'Convertie',
    'chantierDetail.docs.facturesSection': 'Factures et acomptes',
    'chantierDetail.docs.noFactures': 'Aucune facture associée à ce chantier.',
    'chantierDetail.docs.acompte': 'Acompte',
    'chantierDetail.docs.devisRef': 'Devis',
    'chantierDetail.docs.paid': 'Payée',
    'chantierDetail.docs.unpaid': 'Impayée',
    'chantierDetail.expenses.errorPrefix': 'Dépenses indisponibles',
    'chantierDetail.expenses.empty': 'Aucune dépense associée à ce chantier.',
    'chantierDetail.expenses.withReceipt': 'Justificatif',
    'chantierDetail.expenses.withoutReceipt': 'Sans justificatif',
    'chantierDetail.expenses.vatOf': 'dont TVA',
    'chantierDetail.suppliers.errorPrefix': 'Factures fournisseurs indisponibles',
    'chantierDetail.suppliers.empty': 'Aucune facture fournisseur associée à ce chantier.',
    'chantierDetail.suppliers.defaultName': 'Fournisseur',
    'chantierDetail.suppliers.htPrefix': 'HT',
    'chantierDetail.suppliers.vatPrefix': 'TVA',
    'chantierDetail.reports.empty': 'Aucun rapport',

    // ===== AI ASSISTANT (Phase 5C) =====
    'aiAssistant.header.title': 'Assistant IA',
    'aiAssistant.header.conversations': 'Conversations',
    'aiAssistant.header.newConversation': 'Nouvelle conversation',
    'aiAssistant.onboarding.title': 'Avant de commencer 🧞',
    'aiAssistant.onboarding.subtitle': 'Pour mieux vous aider',
    'aiAssistant.onboarding.firstName': 'Votre prénom',
    'aiAssistant.onboarding.firstNamePlaceholder': 'Ex : Ahmed',
    'aiAssistant.onboarding.gender': 'Genre',
    'aiAssistant.onboarding.start': "C'est parti ! 🚀",
    'aiAssistant.conversations.empty': 'Aucune conversation',
    'aiAssistant.conversations.delete': 'Supprimer',
    'aiAssistant.conversations.autoDelete': 'Suppression automatique après 30 jours',
    'aiAssistant.welcome.greeting': 'Bonjour {name}, posez votre question ! 🧞',
    'aiAssistant.welcome.subtitle': 'Posez vos questions',
    'aiAssistant.categories.pro': 'Professionnel',
    'aiAssistant.categories.admin': 'Administratif',
    'aiAssistant.categories.legal': 'Juridique',
    'aiAssistant.categories.personal': 'Personnel',
    'aiAssistant.roomScanner': '📐 Scanner la pièce',
    'aiAssistant.input.placeholder': 'Écrivez votre question…',
    'aiAssistant.input.attach': 'Joindre un fichier',
    'aiAssistant.input.attachTitle': 'Joindre une image ou un PDF',
    'aiAssistant.input.remove': 'Retirer',
    'aiAssistant.file.reading': 'Lecture des fichiers…',
    'aiAssistant.file.unsupported': 'Ce type de fichier n’est pas pris en charge.',
    'aiAssistant.file.tooLarge': 'Fichier trop volumineux.',
    'aiAssistant.file.readError': 'Erreur de lecture du fichier.',
    'aiAssistant.voice.notSupported': 'Le microphone n’est pas disponible.',
    'aiAssistant.typing': 'écrit',
    'aiAssistant.cancelled': '(annulé)',
    'aiAssistant.error.generic': 'Une erreur est survenue. Veuillez réessayer.',
    'aiAssistant.error.network': 'Impossible d’envoyer votre message. Veuillez réessayer.',
    'aiAssistant.missingInfo.reply': 'Voici les informations manquantes :',

    // ===== BOTTOM NAVIGATION (Phase 5C) =====
    'bottomNav.accounting': 'Comptabilité',
    'bottomNav.home': 'Accueil',
    'bottomNav.contact': 'Contactez-nous',
    'bottomNav.account': 'Mon compte',
    'bottomNav.admin': 'Administration',
    'bottomNav.report': 'Rapport',
    'bottomNav.contactShort': 'Contact',
  },

  ar: {
    // ===== NAVIGATION =====
    'nav.dashboard': 'الرئيسية',
    'nav.radio': 'الراديو',
    'nav.assistant': 'استشارات',
    'nav.profile': 'حسابي',
    'nav.pro': 'أدوات',
    'nav.admin': 'الإدارة',

    // ===== HEADER =====
    'header.appName': 'Anafy Pro',
    'header.consultations': 'استشارات',
    'header.proTools': 'دراعك اليمين',
    
    // ===== DASHBOARD =====
    'dashboard.welcome': 'أهلاً بيك في Anafy Pro',
    'dashboard.subtitle': 'مساعدك الشخصي لكل حاجة إدارية',
    'dashboard.quickAccess': 'دخول سريع',
    'dashboard.radioCard': 'الراديو المصري',
    'dashboard.radioDesc': 'اسمع محطاتك المفضلة',
    'dashboard.assistantCard': 'المساعد الذكي',
    'dashboard.assistantDesc': 'هاعملك خطاباتك الرسمية',
    'dashboard.aiBanner': 'اسأل وأنا أجاوبك',
    'dashboard.aiBannerSub': 'بالعربي والفرنساوي',
    'dashboard.cvCard': 'سيرتي الذكية (سي في)',
    'dashboard.cvCardSub': 'Mon CV Pro',
    'dashboard.invoiceCard': 'اعمل فواتيرك ودوفيهاتك ودراسة الجدوى والتكاليف معانا. احنا والذكاء الصناعي واحد',
    'dashboard.invoiceCardSub': 'Devis, Factures & Étude de Rentabilité IA',
    'dashboard.codeRoute': 'كود دو لاروت',
    'dashboard.codeRouteSub': 'دروس وامتحانات بالمصري',
    
    // ===== CHAT QUICK ACTIONS =====
    'chat.action.cv': '👤 عايز تعمل سي في',
    'chat.action.invoice': '📄 عايز تكتب فاتورة',
    'chat.action.mail': '✉️ الرد على خطاب',
    'chat.title': 'شبيك لبيك 🧞‍♂️',
    'chat.subtitle': 'اسأل وانا اجاوب',
    'chat.placeholder': 'اكتب رسالتك...',
    'chat.thinking': 'يفكر...',
    'chat.welcomeTitle': 'أهلا! أنا مساعدك الذكي 🧞‍♂️',
    'chat.welcomeMessage': 'اكتب سؤالك أو ارفع صورة مستند وأنا هساعدك.',
    
    // ===== RADIO =====
    'radio.title': 'الراديو',
    'radio.nowPlaying': 'بيشتغل دلوقتي',
    'radio.selectStation': 'اختار محطة',
    'radio.searchPlaceholder': 'دور على محطة...',
    'radio.categoryEgypt': 'إذاعات مصرية (موسيقى وأخبار)',
    'radio.categoryMaghreb': 'إذاعات المغرب وفرنسا',
    'radio.noResults': 'مافيش نتايج',
    
    // ===== ASSISTANT / CONSULTATIONS =====
    'assistant.title': 'محادثة',
    'assistant.subtitle': 'احكيلي موضوعك وأنا هاساعدك',
    'assistant.textPlaceholder': 'احكيلي إيه المشكلة... (بالعربي أو بالفرنساوي)',
    'assistant.recordVoice': 'سجّل صوتك',
    'assistant.uploadDocument': 'ارفع صورة أو PDF',
    'assistant.analyze': 'حلل',
    'assistant.formalLetter': 'الخطاب الرسمي',
    'assistant.legalNote': 'ملاحظات قانونية',
    'assistant.actionPlan': 'خطة العمل',
    'assistant.copy': 'نسخ',
    'assistant.download': 'حمّل PDF',
    'assistant.newTopic': 'موضوع جديد',
    'assistant.continueSession': 'نكمل',
    'assistant.startNew': 'موضوع جديد',
    'assistant.sessionDialog.title': 'في محادثة قديمة',
    'assistant.sessionDialog.description': 'نكمل الكلام في الموضوع القديم؟',
    'assistant.clearConfirm.title': 'امسح المحادثة؟',
    'assistant.clearConfirm.description': 'كده هتمسح كل الكلام اللي فات.',
    'assistant.dailyLimit': 'الحد اليومي',
    'assistant.dailyLimitDesc': 'وصلت للحد اليومي (30 رسالة). ارجع بكره!',
    'assistant.analyzing': 'بحلل...',
    'assistant.documentReady': 'الخطاب جاهز',
    'assistant.viewDocument': 'شوف الخطاب',
    'assistant.generateLetter': 'اكتبلي خطاب',
    'assistant.generating': 'بكتب...',
    
    // ===== PROFILE =====
    'profile.title': 'بياناتي',
    'profile.fullName': 'الاسم الكامل',
    'profile.firstName': 'الاسم الأول',
    'profile.lastName': 'اللقب',
    'profile.address': 'العنوان',
    'profile.phone': 'التليفون',
    'profile.cafNumber': 'رقم الـ CAF',
    'profile.foreignerNumber': 'رقم الأجانب',
    'profile.socialSecurity': 'رقم السيكوريتيه (Sécu)',
    'profile.save': 'احفظ',
    'profile.optional': '(اختياري)',
    'profile.saved': 'تم الحفظ',
    'profile.savedDesc': 'بياناتك اتحفظت.',
    
    // ===== PRO TOOLS =====
    // ⚠️ TERMES PROTÉGÉS - NE PAS MODIFIER
    'pro.title': 'دراعك اليمين 💪',
    'pro.subtitle': 'كل اللي يحتاجه الصنايعي والحرفي في فرنسا',
    'pro.invoices': 'فواتير ودوفيهات',
    'pro.invoicesDesc': 'اعمل الفاكتير والدوفي بتوعك بسهولة',
    'pro.quoteToInvoice': 'حوّل الدوفي لفاكتير',
    'pro.quoteToInvoiceDesc': 'ارفع الدوفي وأنا أملّي الفاكتير تلقائي!',
    'pro.legal': 'قوانين الشغل والضرايب',
    'pro.legalDesc': 'اعرف حقوقك وواجباتك',
    'pro.cvGenerator': 'صانع CV',
    'pro.cvGeneratorDesc': 'اكتب بالعربي والذكاء الاصطناعي يترجم للفرنسية',
    'pro.cvGeneratorDesc2': 'سي في احترافي في اقل من دقايق',
    'pro.settings': 'بيانات شركتي',
    'pro.settingsDesc': 'الاسم واللوجو والـ SIRET',
    'pro.toolsNotice': 'أدوات مخصصة للصنايعية والحرفيين في فرنسا',
    
    // ===== INVOICE CREATOR =====
    // ⚠️ TERMES PROTÉGÉS
    'invoice.quote': 'عرض سعر (دوفي)',
    'invoice.invoice': 'فاتورة (فاكتير)',
    'invoice.client': 'الزبون',
    'invoice.clientName': 'اسم الزبون',
    'invoice.clientAddress': 'عنوان الزبون',
    'invoice.worksite': 'عنوان الشانتييه',
    'invoice.description': 'الوصف',
    'invoice.quantity': 'الكمية',
    'invoice.unit': 'الوحدة',
    'invoice.unitPrice': 'سعر الوحدة',
    'invoice.total': 'المجموع',
    'invoice.subtotal': 'المجموع قبل الضريبة',
    'invoice.tva': 'TVA',
    'invoice.totalTTC': 'المجموع الكلي TTC',
    'invoice.addLine': 'أضف سطر',
    'invoice.preview': 'معاينة وتحميل PDF',
    'invoice.signature': 'التوقيع',
    'invoice.clientSignature': 'توقيع الزبون',
    'invoice.artisanSignature': 'توقيع الحرفي',
    'invoice.bonPourAccord': 'موافق على العرض',
    'invoice.validUntil': 'الدوفي صالح لغاية',
    'invoice.paymentTerms': 'شروط الدفع',
    
    // ===== CV GENERATOR =====
    'cv.title': 'سيرتي الذاتية',
    'cv.subtitle': 'اكتب بالعربي والذكاء الاصطناعي يترجم للفرنسية',
    'cv.personalInfo': 'البيانات الشخصية',
    'cv.fullName': 'الاسم الكامل',
    'cv.firstName': 'الاسم الأول',
    'cv.lastName': 'اللقب',
    'cv.profession': 'الشغلانة / الوظيفة اللي عايزها',
    'cv.email': 'الإيميل',
    'cv.phone': 'التليفون',
    'cv.address': 'العنوان',
    'cv.summary': 'ملخص عنك',
    'cv.experience': 'خبرتك في الشغل',
    'cv.education': 'التعليم',
    'cv.skills': 'مهاراتك',
    'cv.languages': 'اللغات',
    'cv.translate': 'ترجم للفرنساوي',
    'cv.translating': 'بترجم...',
    'cv.downloadPdf': 'حمّل PDF',
    'cv.preview': 'معاينة',
    'cv.edit': 'تعديل',
    'cv.drivingLicense': 'رخصة السواقة',
    'cv.interests': 'هواياتك',
    
    // ===== COMMON =====
    'common.loading': 'استنى شوية...',
    'common.error': 'حصل مشكلة',
    'common.success': 'تمام',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.save': 'احفظ',
    'common.delete': 'امسح',
    'common.edit': 'عدّل',
    'common.close': 'اقفل',
    'common.back': 'رجوع',
    'common.next': 'اللي بعده',
    'common.previous': 'اللي قبله',
    'common.yes': 'أيوه',
    'common.no': 'لأ',
    'common.or': 'أو',
    'common.and': 'و',
    'common.send': 'ارسل',
    
    // ===== ERRORS =====
    'error.network': 'مشكلة في الاتصال. جرب تاني.',
    'error.timeout': 'الطلب أخد وقت طويل. جرب تاني.',
    'error.generic': 'حصل مشكلة. جرب تاني.',
    'error.invalidAlphabet': 'في حروف مش مسموحة. استخدم عربي أو فرنسي بس.',
    
    // ===== AUTH =====
    'auth.login': 'دخول',
    'auth.signup': 'تسجيل',
    'auth.logout': 'خروج',
    'auth.email': 'الإيميل',
    'auth.password': 'الباسورد',
    'auth.forgotPassword': 'نسيت الباسورد؟',

    // ===== NEWS =====
    'news.title': 'الأخبار',
    'news.subtitle': 'تابع آخر الأخبار',
    'news.disclaimer': 'روابط لمصادر خارجية. Anafy Pro مش مسؤول عن المحتوى.',
    'nav.news': 'أخبار',

    // ===== COURRIER =====
    'courrier.title': 'الرد على خطاب',

    // ===== LEGAL GUIDE =====
    'legal.title': 'دليلك الإداري والقانوني',
    'legal.subtitle': 'تحليل المستندات شغال',
    'legal.welcome': 'أهلاً بيك في دليلك الإداري والقانوني.',
    'legal.welcomeSub': 'ابعت صورة المستند أو اسأل عن حقوقك وأنا هساعدك.',
    'legal.placeholder': 'احكيلي موضوعك أو ابعت صورة المستند...',
    'legal.dashboardTitle': 'دليلك الإداري والقانوني',
    'legal.dashboardSub': 'تحليل مستندات وحقوق',



    // ===== EXPENSES / GESTION COMPTABLE =====
    'expenses.notLoggedIn': 'يرجى تسجيل الدخول',
    'expenses.warningTip': 'هذه الأرقام مبنية على فواتيرك فقط — تواصل مع محاسبك للحسابات الدقيقة',
    'expenses.title': '💰 إدارة الحسابات',
    'expenses.btn.scan': '📷 مسح فاتورة',
    'expenses.btn.add': 'إضافة',
    'expenses.btn.accountantExport': 'تصدير بيانات المحاسب',
    'expenses.btn.archiveDocs': 'تحميل أرشيف المستندات',
    'expenses.section.accounting': 'المحاسبة',
    'expenses.section.documents': 'المستندات',
    'expenses.section.clients': 'العملاء',
    'expenses.section.chantiers': 'مشاريعي (الشانتيات)',
    'expenses.summary.collected': '💰 الأموال المحصلة',
    'expenses.summary.totalExpenses': 'إجمالي المصروفات',
    'expenses.timeline.title': '📋 آخر العمليات',
    'expenses.timeline.empty': 'لا توجد عمليات بعد',
    'expenses.filter.paidAll': 'كل الفواتير',
    'expenses.filter.paidOnly': 'مدفوعة فقط',
    'expenses.filter.unpaidOnly': 'غير مدفوعة فقط',
    'expenses.filter.all': 'الكل',
    'expenses.filter.month': 'هذا الشهر',
    'expenses.filter.quarter': 'هذا الربع',
    'expenses.filter.year': 'هذه السنة',
    'expenses.badge.overdue': 'متأخرة',
    'expenses.diagnostic.label': '🧪 تشخيص: {n} فاتورة مدفوعة',
    'expenses.diagnostic.desc': 'إذا كانت هذه بيانات اختبار، اضغط لإعادة التعيين إلى "غير مدفوع".',
    'expenses.diagnostic.resetAllBtn': 'إعادة تعيين الكل ({n})',
    'expenses.diagnostic.resetAllTitle': 'تأكيد إعادة تعيين الكل',
    'expenses.diagnostic.resetAllDialogDesc': 'سيتم وضع علامة "غير مدفوع" على {n} فاتورة. لن يتم حذف أي مستند.',
    'expenses.diagnostic.unpaidBtn': 'غير مدفوع',
    'expenses.diagnostic.resetClientTitle': 'تأكيد إعادة التعيين',
    'expenses.diagnostic.resetClientDialogDesc': 'سيتم وضع علامة "غير مدفوع" على {n} فاتورة لـ {name}. لن يتم حذف أي مستند.',
    'expenses.admin.title': '🛠️ أدوات المسؤول',
    'expenses.admin.desc': 'يضع كل الفواتير "غير مدفوعة" ويحذف كل المصروفات. لا يتم حذف أي فاتورة أو دوفي.',
    'expenses.admin.resetBtn': 'إعادة تعيين بيانات الاختبار',
    'expenses.admin.resetDialogDesc': 'كل الفواتير ستصبح "غير مدفوعة" وكل المصروفات هتتحذف. الفواتير والدوفيهات لن تُحذف.',
    'expenses.toast.resetOk': '✅ تم',
    'expenses.toast.resetClientDesc': 'تم وضع علامة "غير مدفوع" على فواتير {name}',
    'expenses.toast.resetAllDesc': 'تم وضع علامة "غير مدفوع" على {n} فاتورة',
    'expenses.toast.resetTestDataTitle': '✅ تم إعادة تعيين بيانات الاختبار',
    'expenses.toast.resetTestDataDesc': 'كل الفواتير "غير مدفوعة" وكل المصروفات اتمسحت.',
    'expenses.toast.accountantEmailMissingTitle': 'إيميل المحاسب مفقود',
    'expenses.toast.accountantEmailMissingDesc': 'أضف إيميل المحاسب في الإعدادات أولاً',
    'expenses.toast.accountantSentTitle': '✅ تم إرسال الملفات للمحاسب بنجاح',
    'expenses.toast.accountantSentDesc': 'إلى : {email}',
    'expenses.toast.sendFailedTitle': 'تعذر الإرسال',
    'expenses.toast.sendFailedDesc': 'حاول مرة أخرى لاحقًا',
    'expenses.toast.archiveEmptyTitle': 'الأرشيف فارغ',
    'expenses.toast.archiveEmptyDesc': 'لم يتم العثور على ملفات مرفقة للتحميل',
    'expenses.toast.archiveOkTitle': 'تم تحميل الأرشيف',
    'expenses.toast.archiveOkDesc': 'تم تحميل {n} ملف(ات) في ملف مضغوط',
    'expenses.toast.archiveErrorDesc': 'فشل تحميل الأرشيف',
    // ===== AddExpenseModal =====
    'addExpense.title': 'إضافة مصروف جديد',
    'addExpense.receipt.label': 'صورة الإيصال',
    'addExpense.receipt.change': 'تغيير',
    'addExpense.receipt.analyze': 'تحليل ذكي',
    'addExpense.receipt.camera': '📷 التقاط صورة',
    'addExpense.receipt.gallery': '🖼️ اختر من المكتبة',
    'addExpense.field.title': 'العنوان *',
    'addExpense.field.titlePlaceholder': 'مثال: شراء دهان',
    'addExpense.field.amount': 'المبلغ (€) *',
    'addExpense.field.tva': 'TVA (€)',
    'addExpense.field.amountType': 'نوع المبلغ *',
    'addExpense.field.category': 'الفئة',
    'addExpense.field.date': 'التاريخ',
    'addExpense.field.client': 'اختر العميل',
    'addExpense.field.clientPlaceholder': 'اختر عميل...',
    'addExpense.field.chantier': 'اختر المشروع',
    'addExpense.field.chantierPlaceholder': 'اختر مشروع...',
    'addExpense.field.docLink': 'ربط بمستند (اختياري)',
    'addExpense.field.docLinkPlaceholder': 'اختر دوفي أو فاتورة',
    'addExpense.field.docLinkNone': 'بدون ربط',
    'addExpense.field.notes': 'ملاحظات',
    'addExpense.field.notesPlaceholder': 'ملاحظات إضافية...',
    'addExpense.save': 'حفظ المصروف',
    'addExpense.toast.analyzeOk': '✅ تم التحليل بنجاح',
    'addExpense.toast.analyzeErr': '⚠️ خطأ في التحليل',
    'addExpense.toast.analyzeErrDesc': 'حاول مرة أخرى أو أدخل البيانات يدوياً',
    'addExpense.toast.missingTitle': '⚠️ بيانات ناقصة',
    'addExpense.toast.missingDesc': 'العنوان والمبلغ مطلوبين',
    'addExpense.toast.added': '✅ تمت إضافة المصروف',
    'addExpense.toast.err': '❌ خطأ',
    'addExpense.cat.materials': 'مواد',
    'addExpense.cat.tools': 'أدوات',
    'addExpense.cat.transport': 'نقل',
    'addExpense.cat.food': 'وجبات',
    'addExpense.cat.office': 'لوازم مكتبية',
    'addExpense.cat.insurance': 'تأمين',
    'addExpense.cat.telecom': 'اتصالات',
    'addExpense.cat.other': 'أخرى',

    // ===== SUPPLIER INVOICES (LIST) =====
    'supplierInvoices.title': 'فواتير المورّدين',
    'supplierInvoices.count.suffix': 'فاتورة',
    'supplierInvoices.ttcSuffix': 'شامل الضريبة',
    'supplierInvoices.import': 'استيراد فاتورة',
    'supplierInvoices.source.label': 'المصدر',
    'supplierInvoices.source.all': 'الكل',
    'supplierInvoices.empty': 'لا توجد فواتير بعد',
    'supplierInvoices.noSupplier': 'بدون مورّد',
    'supplierInvoices.htPrefix': 'بدون ضريبة',
    'supplierInvoices.status.received': 'مستلمة',
    'supplierInvoices.status.processed': 'معالجة',
    'supplierInvoices.status.paid': 'مدفوعة',
    'supplierInvoices.toast.loadError': 'خطأ في تحميل الفواتير',
    // ===== SUPPLIER INVOICE DETAIL =====
    'supplierInvoiceDetail.back': 'رجوع',
    'supplierInvoiceDetail.noSupplier': 'بدون مورّد',
    'supplierInvoiceDetail.siret': 'SIRET',
    'supplierInvoiceDetail.date': 'التاريخ',
    'supplierInvoiceDetail.source': 'المصدر',
    'supplierInvoiceDetail.supplierReference': 'مرجع المورّد',
    'supplierInvoiceDetail.amountHT': 'المبلغ بدون ضريبة',
    'supplierInvoiceDetail.tva': 'ضريبة القيمة المضافة',
    'supplierInvoiceDetail.ttc': 'شامل الضريبة',
    'supplierInvoiceDetail.chantier.title': 'الورشة المرتبطة',
    'supplierInvoiceDetail.chantier.placeholder': 'اختر ورشة',
    'supplierInvoiceDetail.chantier.none': '— بدون ورشة —',
    'supplierInvoiceDetail.chantier.remove': 'إزالة',
    'supplierInvoiceDetail.chantier.note': 'لا يغيّر المبلغ ولا الضريبة ولا الـPDF ولا المحاسبة.',
    'supplierInvoiceDetail.chantier.toastAttached': 'تم ربط الفاتورة بالورشة.',
    'supplierInvoiceDetail.chantier.toastDetached': 'تم فصل الفاتورة عن الورشة.',
    'supplierInvoiceDetail.expense.title': 'المصروف المرتبط',
    'supplierInvoiceDetail.expense.placeholder': 'اختر مصروفاً',
    'supplierInvoiceDetail.expense.none': '— بدون مصروف —',
    'supplierInvoiceDetail.expense.alreadyLinked': 'مرتبط مسبقاً',
    'supplierInvoiceDetail.expense.note': 'ربط هذه الفاتورة بالمصروف المقابل يمنع الحساب المزدوج في ربحية الورشة.',
    'supplierInvoiceDetail.expense.toastAttached': 'تم ربط المصروف بالفاتورة.',
    'supplierInvoiceDetail.expense.toastDetached': 'تم فصل المصروف.',
    'supplierInvoiceDetail.lines.title': 'بنود الفاتورة',
    'supplierInvoiceDetail.accounting.title': 'المحاسبة — يومية ACH',
    'supplierInvoiceDetail.accounting.subtitle': 'القيود المُولَّدة تلقائياً وتُدرَج في تصدير FEC',
    'supplierInvoiceDetail.accounting.account': 'الحساب',
    'supplierInvoiceDetail.accounting.label': 'البيان',
    'supplierInvoiceDetail.accounting.debit': 'مدين',
    'supplierInvoiceDetail.accounting.credit': 'دائن',
    'supplierInvoiceDetail.accounting.total': 'المجموع',
    'supplierInvoiceDetail.accounting.purchases': 'مشتريات مواد أولية',
    'supplierInvoiceDetail.accounting.tvaDeductible': 'ضريبة قابلة للخصم',
    'supplierInvoiceDetail.accounting.suppliers': 'المورّدون',
    'supplierInvoiceDetail.viewOriginal': 'عرض الفاتورة الأصلية',
    'supplierInvoiceDetail.downloadOriginal': 'تحميل الفاتورة الأصلية',
    'supplierInvoiceDetail.originalUnavailable': 'الفاتورة الأصلية غير متاحة مؤقتاً',
    'supplierInvoiceDetail.originalMissing': 'الفاتورة الأصلية غير متوفرة',
    'supplierInvoiceDetail.markPaid': 'تحديد كمدفوعة',
    'supplierInvoiceDetail.markPaidToast': 'تم تحديدها كمدفوعة',
    'supplierInvoiceDetail.genericError': 'حدث خطأ',

    // ===== CHANTIER DETAIL =====
    'chantierDetail.loading': 'جاري التحميل...',
    'chantierDetail.notFound': 'المشروع مش موجود',
    'chantierDetail.status.etude': 'قيد الدراسة',
    'chantierDetail.status.devis_envoye': 'تم إرسال الدوفي',
    'chantierDetail.status.en_cours_travaux': 'شغل جاري',
    'chantierDetail.status.facture_envoyee': 'تم إرسال الفاتورة',
    'chantierDetail.status.paiement_attente': 'فاتورة قيد التحصيل',
    'chantierDetail.status.facture_payee': 'تم تحصيل الفاتورة',
    'chantierDetail.alert.red': 'خطر: المصاريف عدّت الميزانية! الربح في خطر',
    'chantierDetail.alert.yellow': 'انتبه: المصاريف قربت من الميزانية',
    'chantierDetail.budget.title': 'ميزانية المشروع',
    'chantierDetail.budget.edit': 'تعديل',
    'chantierDetail.budget.expected': 'الميزانية المتوقعة',
    'chantierDetail.budget.invoiced': 'المبلغ المفوتر',
    'chantierDetail.budget.progress': 'تقدم الميزانية',
    'chantierDetail.budget.label': 'ميزانية المشروع (€)',
    'chantierDetail.budget.save': 'حفظ',
    'chantierDetail.budget.cancel': 'إلغاء',
    'chantierDetail.budget.add': '+ إضافة ميزانية المشروع',
    'chantierDetail.budget.savedToast': 'تم حفظ الميزانية ✓',
    'chantierDetail.toast.errorTitle': 'خطأ',
    'chantierDetail.toast.saveError': 'ما قدرناش نحفظ الميزانية',
    'chantierDetail.actions.createInvoice': 'إنشاء فاتورة',
    'chantierDetail.actions.addExpense': 'إضافة مصروف',
    'chantierDetail.synthese.devis': 'دوفي',
    'chantierDetail.synthese.devisHint': 'إرشادي',
    'chantierDetail.synthese.factured': 'مفوتر',
    'chantierDetail.synthese.encaisse': 'محصّل',
    'chantierDetail.synthese.reste': 'الباقي للتحصيل',
    'chantierDetail.synthese.expenses': 'مصاريف',
    'chantierDetail.synthese.suppliers': 'فواتير الموردين',
    'chantierDetail.marginNote': 'الهامش المتاح بعد جمع المصاريف. تقدير مبني على المستندات المربوطة حالياً بالمشروع.',
    'chantierProfitability.title': 'ربحية المشروع',
    'chantierProfitability.status.rentable': 'مشروع مربح',
    'chantierProfitability.status.surveiller': 'مشروع للمتابعة',
    'chantierProfitability.status.deficitaire': 'مشروع خسران',
    'chantierProfitability.status.incomplet': 'حساب غير مكتمل',
    'chantierProfitability.revenueHT': 'الإيراد بدون ضريبة',
    'chantierProfitability.costsHT': 'التكاليف بدون ضريبة',
    'chantierProfitability.marginHT': 'الهامش بدون ضريبة',
    'chantierProfitability.freeExpensesHT': 'مصاريف حرة بدون ضريبة',
    'chantierProfitability.supplierHT': 'فواتير موردين بدون ضريبة',
    'chantierProfitability.antiDoublonNote': 'تقدير بدون ضريبة. منع التكرار: المصاريف المربوطة بفاتورة مورد تتحسب مرة واحدة (عن طريق الفاتورة).',
    'chantierDetail.tabs.documents': 'المستندات',
    'chantierDetail.tabs.expenses': 'المصاريف',
    'chantierDetail.tabs.suppliers': 'الموردين',
    'chantierDetail.tabs.reports': 'التقارير',
    'chantierDetail.docs.errorPrefix': 'المستندات غير متاحة',
    'chantierDetail.docs.devisSection': 'الدوفيات',
    'chantierDetail.docs.noDevis': 'مافيش دوفي مربوط بالمشروع.',
    'chantierDetail.docs.converted': 'تم التحويل',
    'chantierDetail.docs.facturesSection': 'الفواتير والمقدمات',
    'chantierDetail.docs.noFactures': 'مافيش فاتورة مربوطة بالمشروع.',
    'chantierDetail.docs.acompte': 'مقدم',
    'chantierDetail.docs.devisRef': 'دوفي',
    'chantierDetail.docs.paid': 'مدفوعة',
    'chantierDetail.docs.unpaid': 'غير مدفوعة',
    'chantierDetail.expenses.errorPrefix': 'المصاريف غير متاحة',
    'chantierDetail.expenses.empty': 'مافيش مصاريف مربوطة بالمشروع.',
    'chantierDetail.expenses.withReceipt': 'مع إثبات',
    'chantierDetail.expenses.withoutReceipt': 'بدون إثبات',
    'chantierDetail.expenses.vatOf': 'منها ضريبة',
    'chantierDetail.suppliers.errorPrefix': 'فواتير الموردين غير متاحة',
    'chantierDetail.suppliers.empty': 'مافيش فاتورة مورد مربوطة بالمشروع.',
    'chantierDetail.suppliers.defaultName': 'مورد',
    'chantierDetail.suppliers.htPrefix': 'بدون ضريبة',
    'chantierDetail.suppliers.vatPrefix': 'ضريبة',
    'chantierDetail.reports.empty': 'مافيش تقارير',

    // ===== AI ASSISTANT (Phase 5C) =====
    'aiAssistant.header.title': 'المساعد الذكي',
    'aiAssistant.header.conversations': 'المحادثات',
    'aiAssistant.header.newConversation': 'محادثة جديدة',
    'aiAssistant.onboarding.title': 'قبل ما نبدأ يا فندم 🧞',
    'aiAssistant.onboarding.subtitle': 'عشان أقدر أساعدك بشكل أفضل',
    'aiAssistant.onboarding.firstName': 'اسمك الأول',
    'aiAssistant.onboarding.firstNamePlaceholder': 'مثلاً: أحمد',
    'aiAssistant.onboarding.gender': 'النوع',
    'aiAssistant.onboarding.start': 'يلا نبدأ! 🚀',
    'aiAssistant.conversations.empty': 'مفيش محادثات لسه',
    'aiAssistant.conversations.delete': 'حذف',
    'aiAssistant.conversations.autoDelete': 'المحادثات بتتمسح أوتوماتيكي بعد 30 يوم',
    'aiAssistant.welcome.greeting': 'أهلاً يا {name}، اسأل وأنا أجاوب! 🧞',
    'aiAssistant.welcome.subtitle': 'اسألني أي حاجة',
    'aiAssistant.categories.pro': 'مهني',
    'aiAssistant.categories.admin': 'إداري',
    'aiAssistant.categories.legal': 'قانوني',
    'aiAssistant.categories.personal': 'شخصي',
    'aiAssistant.roomScanner': '📐 سكانير الغرفة',
    'aiAssistant.input.placeholder': 'اكتب سؤالك هنا...',
    'aiAssistant.input.attach': 'إرفاق ملف',
    'aiAssistant.input.attachTitle': 'إرفاق صورة أو PDF',
    'aiAssistant.input.remove': 'حذف',
    'aiAssistant.file.reading': 'جاري قراءة الملفات...',
    'aiAssistant.file.unsupported': 'نوع الملف غير مدعوم',
    'aiAssistant.file.tooLarge': 'الملف كبير أوي',
    'aiAssistant.file.readError': 'حصل مشكلة في الملف',
    'aiAssistant.voice.notSupported': 'الميكروفون مش شغال دلوقتي',
    'aiAssistant.typing': 'يكتب',
    'aiAssistant.cancelled': '(تم الإلغاء)',
    'aiAssistant.error.generic': 'حصلت مشكلة، جرب تاني من فضلك 🔄',
    'aiAssistant.error.network': 'مقدرناش نبعت رسالتك، جرب تاني 🔄',
    'aiAssistant.missingInfo.reply': 'هاكي البيانات الناقصة:',

    // ===== BOTTOM NAVIGATION (Phase 5C) =====
    'bottomNav.accounting': 'المحاسبة',
    'bottomNav.home': 'الرئيسية',
    'bottomNav.contact': 'تواصل معنا',
    'bottomNav.account': 'حسابي',
    'bottomNav.admin': 'الإدارة',
    'bottomNav.report': 'تقرير الشانتي',
    'bottomNav.contactShort': 'تواصل',
  },

};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('ana-fi-france-lang');
      // Fallback global = français si valeur absente ou invalide
      return saved === 'ar' || saved === 'fr' ? (saved as Language) : 'fr';
    } catch {
      return 'fr';
    }
  });

  const isRTL = language === 'ar';

  const setLanguage = (lang: Language) => {
    const safe: Language = lang === 'ar' ? 'ar' : 'fr';
    setLanguageState(safe);
  };

  useEffect(() => {
    try { localStorage.setItem('ana-fi-france-lang', language); } catch {}
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
